---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.
custom_structured_configuration_prefix: ['my_dci_']

fabric_name: FABRIC

# Enable vlan aware bundles

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

#
# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

# Update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

# List of additional CVP configlets to bind to devices and containers
# Configlets MUST be configured on CVP before running AVD playbooks.

# cv_configlets:
#   containers:
#     DC1_L3LEAFS:
#       - ASE_GLOBAL-ALIASES

# cv_configlets:
#   devices:
#     borderleaf1-DC1:
#       - DCI_borderleaf1-DC1
#     borderleaf2-DC1:
#       - DCI_borderleaf2-DC1
#     borderleaf1-DC2:
#       - DCI_borderleaf1-DC2
#     borderleaf2-DC2:
#       - DCI_borderleaf2-DC2
#     DCI:
#       - AVD_DCI_Switch


local_users:
  ansible_local:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

# Cloud Vision server information
cvp_instance_ip: 192.168.0.5
cvp_ingestauth_key: 'atd-lab'

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
# If ATD is running cEOS, management interface is Management0
# If ATD is running vEOS, management interface is Management1
mgmt_interface: Management0
mgmt_interface_vrf: default

# dns servers.
name_servers:
  - 192.168.2.1
  - 8.8.8.8

# dns domain
dns_domain: atd.lab

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
# ntp_servers:
#  - 192.168.0.1

radius_servers:
  - host: 192.168.0.1
    # vrf: default
    key: 0207165218120E

aaa_server_groups:
  - name: atds
    type: radius
    servers:
      - server: 192.168.0.1
        # vrf: default
