---
CVP_DEVICES_INIT:
  - fqdn: spine1-DC1
    parentContainerName: STAGING
    configlets:
      - 'spine1-DC1-BASE'
      - 'ATD-INFRA'
  - fqdn: spine2-DC1
    parentContainerName: STAGING
    configlets:
      - 'spine2-DC1-BASE'
      - 'ATD-INFRA'
  - fqdn: spine3-DC1
    parentContainerName: STAGING
    configlets:
      - 'spine3-DC1-BASE'
      - 'ATD-INFRA'
  - fqdn: leaf1-DC1
    parentContainerName: STAGING
    configlets:
      - 'leaf1-DC1-BASE'
      - 'ATD-INFRA'
  - fqdn: leaf2-DC1
    parentContainerName: STAGING
    configlets:
      - 'leaf2-DC1-BASE'
      - 'ATD-INFRA'
  - fqdn: leaf3-DC1
    parentContainerName: STAGING
    configlets:
      - 'leaf3-DC1-BASE'
      - 'ATD-INFRA'
  - fqdn: leaf4-DC1
    parentContainerName: STAGING
    configlets:
      - 'leaf4-DC1-BASE'
      - 'ATD-INFRA'
  - fqdn: borderleaf1-DC1
    parentContainerName: STAGING
    configlets:
      - 'borderleaf1-DC1-BASE'
      - 'ATD-INFRA'
  - fqdn: borderleaf2-DC1
    parentContainerName: STAGING
    configlets:
      - 'borderleaf2-DC1-BASE'
      - 'ATD-INFRA'

CVP_CONTAINERS_INIT:
  STAGING:
    parentContainerName: Tenant
  Hosts:
    parentContainerName: Tenant
  CVX:
    parentContainerName: Tenant

CVP_CONTAINERS_DELETE:
  Leaf-DC1:
    parentContainerName: DC1
  Spine-DC1:
    parentContainerName: DC1
