- name: "Run Fabric states validation"
  hosts: DC2_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:

    - name: deploy configuration to device
      import_role:
         name: arista.avd.eos_validate_state