---
  - name: Provision ATD environment to prepare AVD Lab
    hosts: cv_servers
    connection: local
    gather_facts: no
    collections:
       - arista.cvp
       - arista.avd
    vars:
      execute_tasks: true
    tasks:
       - name: Run AVD Provisioner
         import_role:
           name: 'atd_provisioner'