---
- name: Assign configlets to devices for DCI
  hosts: cvp1

  vars:
    path: "{{lookup('env','PWD')}}"
  vars_files:
    - ../vars/DCI_topology.yml

  tasks:
    - name: "Uploading configlets for DCI"
      arista.cvp.cv_configlet_v3:
        configlets: "{{ DCI_Configlets }}"

    - name: Apply DCI configlets
      arista.cvp.cv_device_v3:
        devices: "{{ DCI_Devices }}"
        state: present
