---
- name: Generate DCI Configuration
  hosts: DCI
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
  - name: Generate Configuration
    tags: [DCI]
    import_role:
      name: eos_cli_config_gen
  - name: provision CVP with AVD configuration
    import_role:
      name: arista.avd.eos_config_deploy_cvp
    vars:
      container_root: 'DCI'
      configlets_prefix: 'AVD_'
            state: present
